### ISSUE TITLE
Project review

### ISSUE THREAD

**Issue by mmorey** [mmorey/StoryboardHelper#1]
@tLewisII what do you think of this? Any feedback? Anything I can do to improve the README?

**Comment by mmorey** [comment]
@Cananito any thoughts on this?

**Comment by Cananito** [comment]
Seems solid. The only two things I can think of improving would be:
1. Auto add the generated file to the project and correct targets (probably not worth it though).
2. Test if it works by adding a `Run Script` build phase to the project, changing from `/bin/sh` to the swift one, and pasting the script there. If so, add README instructions for it? That's a more GUI friendly way to use this (that way you don't have to chmod the file).

**Comment by tLewisII** [comment]
@mmorey I don't think it is very useful until it also generates code to instantiate each view controller that is in each storyboard.

**Comment by mmorey** [comment]
@tLewisII this [tool](https://github.com/paulsamuels/SBConstants) turns storyboard identifiers into constants. This tool just builds on top of that.
